name: Tests
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: [ '7.4', '8.0']
        sf_version: [ '5.1.*', '5.0.*', '5.2.*', '5.3.*' ]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.5.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.sf_version }}
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader --prefer-stable

      - name: Run tests
        run: ./vendor/bin/phpunit
